# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
