# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170812_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_url',
            new_name='picture_url',
        ),
    ]
