# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:47
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buy_in_intervals',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='chip_basic_unit',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='default_min_bet',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
