# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170911_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(default='1.2', max_length=255),
        ),
    ]
