# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
