# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170807_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.Game'),
        ),
    ]
