# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_bet_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='result',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
